[2025-09-16T17:02:36.130+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T17:02:36.198+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-16T14:45:00+00:00 [queued]>
[2025-09-16T17:02:36.214+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-16T14:45:00+00:00 [queued]>
[2025-09-16T17:02:36.215+0200] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-09-16T17:02:36.246+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-16 14:45:00+00:00
[2025-09-16T17:02:36.266+0200] {standard_task_runner.py:64} INFO - Started process 265 to run task
[2025-09-16T17:02:36.274+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-16T14:45:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmppy1_dv1j']
[2025-09-16T17:02:36.279+0200] {standard_task_runner.py:91} INFO - Job 27: Subtask dbt_deps
[2025-09-16T17:02:36.430+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-16T14:45:00+00:00 [running]> on host 1621268d5064
[2025-09-16T17:02:36.903+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T14:45:00+00:00'
[2025-09-16T17:02:36.905+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T17:02:36.917+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T17:02:36.918+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-16T17:02:36.934+0200] {subprocess.py:86} INFO - Output:
[2025-09-16T17:02:39.346+0200] {subprocess.py:93} INFO - [0m15:02:39  Running with dbt=1.8.3
[2025-09-16T17:02:40.921+0200] {subprocess.py:93} INFO - [0m15:02:40  Installing dbt-labs/dbt_utils
[2025-09-16T17:02:48.605+0200] {subprocess.py:93} INFO - [0m15:02:48  Installed from version 1.3.1
[2025-09-16T17:02:48.607+0200] {subprocess.py:93} INFO - [0m15:02:48  Up to date!
[2025-09-16T17:02:49.769+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-16T17:02:49.771+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T17:02:49.824+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-16T14:45:00+00:00, execution_date=20250916T144500, start_date=20250916T150236, end_date=20250916T150249
[2025-09-16T17:02:49.880+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-16T17:02:49.911+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T17:02:49.914+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
