[2025-09-15T21:45:07.772+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-15T21:45:07.934+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T19:30:00+00:00 [queued]>
[2025-09-15T21:45:07.966+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T19:30:00+00:00 [queued]>
[2025-09-15T21:45:07.970+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-15T21:45:08.008+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 19:30:00+00:00
[2025-09-15T21:45:08.025+0200] {standard_task_runner.py:64} INFO - Started process 1609 to run task
[2025-09-15T21:45:08.035+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T19:30:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpzj6_4hg3']
[2025-09-15T21:45:08.044+0200] {standard_task_runner.py:91} INFO - Job 46: Subtask dbt_deps
[2025-09-15T21:45:08.226+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T19:30:00+00:00 [running]> on host f51a750ef2c3
[2025-09-15T21:45:08.957+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T19:30:00+00:00'
[2025-09-15T21:45:08.959+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-15T21:45:09.000+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T21:45:09.002+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-15T21:45:09.037+0200] {subprocess.py:86} INFO - Output:
[2025-09-15T21:45:11.232+0200] {subprocess.py:93} INFO - [0m19:45:11  Running with dbt=1.8.3
[2025-09-15T21:45:12.678+0200] {subprocess.py:93} INFO - [0m19:45:12  Installing dbt-labs/dbt_utils
[2025-09-15T21:45:19.897+0200] {subprocess.py:93} INFO - [0m19:45:19  Installed from version 1.3.1
[2025-09-15T21:45:19.899+0200] {subprocess.py:93} INFO - [0m19:45:19  Up to date!
[2025-09-15T21:45:21.039+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-15T21:45:21.041+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-15T21:45:21.095+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T19:30:00+00:00, execution_date=20250915T193000, start_date=20250915T194507, end_date=20250915T194521
[2025-09-15T21:45:21.161+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-15T21:45:21.193+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-15T21:45:21.196+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
