[2025-09-19T03:00:03.028+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T03:00:03.076+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-19T00:45:00+00:00 [queued]>
[2025-09-19T03:00:03.089+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-19T00:45:00+00:00 [queued]>
[2025-09-19T03:00:03.090+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-19T03:00:03.105+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-19 00:45:00+00:00
[2025-09-19T03:00:03.112+0200] {standard_task_runner.py:64} INFO - Started process 298 to run task
[2025-09-19T03:00:03.117+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-19T00:45:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpnxufrft9']
[2025-09-19T03:00:03.121+0200] {standard_task_runner.py:91} INFO - Job 26: Subtask dbt_deps
[2025-09-19T03:00:03.227+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-19T00:45:00+00:00 [running]> on host 286d1f3cd4b3
[2025-09-19T03:00:03.516+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T00:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T00:45:00+00:00'
[2025-09-19T03:00:03.517+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T03:00:03.529+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-19T03:00:03.531+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-19T03:00:03.550+0200] {subprocess.py:86} INFO - Output:
[2025-09-19T03:00:05.493+0200] {subprocess.py:93} INFO - [0m01:00:05  Running with dbt=1.8.3
[2025-09-19T03:00:06.494+0200] {subprocess.py:93} INFO - [0m01:00:06  Installing dbt-labs/dbt_utils
[2025-09-19T03:00:12.268+0200] {subprocess.py:93} INFO - [0m01:00:12  Installed from version 1.3.1
[2025-09-19T03:00:12.269+0200] {subprocess.py:93} INFO - [0m01:00:12  Up to date!
[2025-09-19T03:00:13.139+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-19T03:00:13.141+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T03:00:13.188+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-19T00:45:00+00:00, execution_date=20250919T004500, start_date=20250919T010003, end_date=20250919T010013
[2025-09-19T03:00:13.265+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-19T03:00:13.288+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-19T03:00:13.292+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
