[2025-09-17T16:00:06.186+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-17T16:00:06.423+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T13:45:00+00:00 [queued]>
[2025-09-17T16:00:06.474+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T13:45:00+00:00 [queued]>
[2025-09-17T16:00:06.481+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-17T16:00:06.530+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-17 13:45:00+00:00
[2025-09-17T16:00:06.553+0200] {standard_task_runner.py:64} INFO - Started process 238 to run task
[2025-09-17T16:00:06.565+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-17T13:45:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpase0e66c']
[2025-09-17T16:00:06.576+0200] {standard_task_runner.py:91} INFO - Job 63: Subtask dbt_deps
[2025-09-17T16:00:06.853+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T13:45:00+00:00 [running]> on host 1621268d5064
[2025-09-17T16:00:07.647+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T13:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T13:45:00+00:00'
[2025-09-17T16:00:07.649+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-17T16:00:07.664+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T16:00:07.666+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-17T16:00:07.700+0200] {subprocess.py:86} INFO - Output:
[2025-09-17T16:00:10.724+0200] {subprocess.py:93} INFO - [0m14:00:10  Running with dbt=1.8.3
[2025-09-17T16:00:11.951+0200] {subprocess.py:93} INFO - [0m14:00:11  Installing dbt-labs/dbt_utils
[2025-09-17T16:00:19.220+0200] {subprocess.py:93} INFO - [0m14:00:19  Installed from version 1.3.1
[2025-09-17T16:00:19.221+0200] {subprocess.py:93} INFO - [0m14:00:19  Up to date!
[2025-09-17T16:00:20.256+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-17T16:00:20.258+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-17T16:00:20.312+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-17T13:45:00+00:00, execution_date=20250917T134500, start_date=20250917T140006, end_date=20250917T140020
[2025-09-17T16:00:20.366+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-17T16:00:20.384+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
