[2025-09-15T23:04:11.480+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-15T23:04:11.588+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:45:00+00:00 [queued]>
[2025-09-15T23:04:11.612+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:45:00+00:00 [queued]>
[2025-09-15T23:04:11.614+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-15T23:04:11.645+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 20:45:00+00:00
[2025-09-15T23:04:11.661+0200] {standard_task_runner.py:64} INFO - Started process 229 to run task
[2025-09-15T23:04:11.670+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T20:45:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmpavb62dvv']
[2025-09-15T23:04:11.680+0200] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_deps
[2025-09-15T23:04:11.850+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:45:00+00:00 [running]> on host 9619aa1d725b
[2025-09-15T23:04:12.534+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T20:45:00+00:00'
[2025-09-15T23:04:12.539+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-15T23:04:12.578+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T23:04:12.595+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-15T23:04:12.643+0200] {subprocess.py:86} INFO - Output:
[2025-09-15T23:04:17.388+0200] {subprocess.py:93} INFO - [0m21:04:17  Running with dbt=1.8.3
[2025-09-15T23:04:18.766+0200] {subprocess.py:93} INFO - [0m21:04:18  Installing dbt-labs/dbt_utils
[2025-09-15T23:04:28.438+0200] {subprocess.py:93} INFO - [0m21:04:28  Installed from version 1.3.1
[2025-09-15T23:04:28.453+0200] {subprocess.py:93} INFO - [0m21:04:28  Up to date!
[2025-09-15T23:04:29.840+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-15T23:04:29.843+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-15T23:04:29.920+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T20:45:00+00:00, execution_date=20250915T204500, start_date=20250915T210411, end_date=20250915T210429
[2025-09-15T23:04:29.988+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-15T23:04:30.033+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-15T23:04:30.036+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
