[2025-09-15T22:15:11.478+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-15T22:15:11.568+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:00:00+00:00 [queued]>
[2025-09-15T22:15:11.584+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:00:00+00:00 [queued]>
[2025-09-15T22:15:11.585+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-15T22:15:11.609+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-15 20:00:00+00:00
[2025-09-15T22:15:11.619+0200] {standard_task_runner.py:64} INFO - Started process 1962 to run task
[2025-09-15T22:15:11.625+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-15T20:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmplnu2qaaa']
[2025-09-15T22:15:11.630+0200] {standard_task_runner.py:91} INFO - Job 56: Subtask dbt_deps
[2025-09-15T22:15:11.786+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-15T20:00:00+00:00 [running]> on host f51a750ef2c3
[2025-09-15T22:15:12.387+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T20:00:00+00:00'
[2025-09-15T22:15:12.389+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-15T22:15:12.417+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T22:15:12.420+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-15T22:15:12.451+0200] {subprocess.py:86} INFO - Output:
[2025-09-15T22:15:16.751+0200] {subprocess.py:93} INFO - [0m20:15:16  Running with dbt=1.8.3
[2025-09-15T22:15:18.110+0200] {subprocess.py:93} INFO - [0m20:15:18  Installing dbt-labs/dbt_utils
[2025-09-15T22:15:23.890+0200] {subprocess.py:93} INFO - [0m20:15:23  Installed from version 1.3.1
[2025-09-15T22:15:23.891+0200] {subprocess.py:93} INFO - [0m20:15:23  Up to date!
[2025-09-15T22:15:24.986+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-15T22:15:24.988+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-15T22:15:25.039+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-15T20:00:00+00:00, execution_date=20250915T200000, start_date=20250915T201511, end_date=20250915T201525
[2025-09-15T22:15:25.082+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-15T22:15:25.112+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-15T22:15:25.115+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
