[2025-09-17T18:45:06.837+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-17T18:45:06.921+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T16:30:00+00:00 [queued]>
[2025-09-17T18:45:06.946+0200] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T16:30:00+00:00 [queued]>
[2025-09-17T18:45:06.947+0200] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-09-17T18:45:06.974+0200] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-17 16:30:00+00:00
[2025-09-17T18:45:06.989+0200] {standard_task_runner.py:64} INFO - Started process 2212 to run task
[2025-09-17T18:45:06.996+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_api_to_bi', 'dbt_deps', 'scheduled__2025-09-17T16:30:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/etl_api_to_bi.py', '--cfg-path', '/tmp/tmp8rp9802m']
[2025-09-17T18:45:07.000+0200] {standard_task_runner.py:91} INFO - Job 123: Subtask dbt_deps
[2025-09-17T18:45:07.205+0200] {task_command.py:426} INFO - Running <TaskInstance: etl_api_to_bi.dbt_deps scheduled__2025-09-17T16:30:00+00:00 [running]> on host 1621268d5064
[2025-09-17T18:45:07.868+0200] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data' AIRFLOW_CTX_DAG_ID='etl_api_to_bi' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T16:30:00+00:00'
[2025-09-17T18:45:07.871+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-17T18:45:07.900+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-17T18:45:07.905+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "docker exec dbt bash -lc 'cd /usr/app && dbt deps --profiles-dir /root/.dbt'"]
[2025-09-17T18:45:07.926+0200] {subprocess.py:86} INFO - Output:
[2025-09-17T18:45:08.570+0200] {subprocess.py:93} INFO - [0m16:45:08  Running with dbt=1.8.3
[2025-09-17T18:45:10.446+0200] {subprocess.py:93} INFO - [0m16:45:10  Installing dbt-labs/dbt_utils
[2025-09-17T18:45:19.531+0200] {subprocess.py:93} INFO - [0m16:45:19  Installed from version 1.3.1
[2025-09-17T18:45:19.534+0200] {subprocess.py:93} INFO - [0m16:45:19  Up to date!
[2025-09-17T18:45:21.215+0200] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-17T18:45:21.218+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-17T18:45:21.305+0200] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_api_to_bi, task_id=dbt_deps, run_id=scheduled__2025-09-17T16:30:00+00:00, execution_date=20250917T163000, start_date=20250917T164506, end_date=20250917T164521
[2025-09-17T18:45:21.484+0200] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-17T18:45:21.521+0200] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-17T18:45:21.526+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
